//! Script API metadata.
//!
//! This module defines a host-owned, versioned, structured description of the
//! scripting API surface. It is intended to be consumed by:
//! - The script editor (autocomplete/hover/docs)
//! - In-script introspection helpers (describe/help/doc)
//! - Future non-Rhai language bindings
//!
//! It must remain independent of the scripting language implementation.

use serde::{Deserialize, Serialize};

pub const SCRIPT_API_SCHEMA_VERSION: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScriptApiMetadata {
    pub schema_version: u32,
    /// Human-readable API version (currently the crate version).
    pub api_version: String,
    pub globals: Vec<ApiGlobal>,
    pub types: Vec<ApiType>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ApiGlobalKind {
    Object,
    Function,
    Variable,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiGlobal {
    pub name: String,
    pub kind: ApiGlobalKind,
    /// Reference to an ApiType name, or a primitive like "float".
    pub type_name: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ApiTypeKind {
    Namespace,
    Struct,
    Opaque,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiType {
    pub name: String,
    pub kind: ApiTypeKind,
    pub description: String,
    pub properties: Vec<ApiProperty>,
    pub methods: Vec<ApiMethod>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiProperty {
    pub name: String,
    pub type_name: String,
    pub description: String,
    #[serde(default)]
    pub readonly: bool,
    #[serde(default)]
    pub optional: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiMethod {
    pub name: String,
    pub description: String,
    pub params: Vec<ApiParam>,
    pub returns: String,
    #[serde(default)]
    pub overload_id: Option<String>,
    #[serde(default)]
    pub example: Option<String>,
    #[serde(default)]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiParam {
    pub name: String,
    pub type_name: String,
    pub description: String,
    #[serde(default)]
    pub optional: bool,
    #[serde(default)]
    pub default: Option<serde_json::Value>,
}

/// The canonical Script API metadata used by Octoseq.
pub fn script_api_metadata() -> ScriptApiMetadata {
    ScriptApiMetadata {
        schema_version: SCRIPT_API_SCHEMA_VERSION,
        api_version: env!("CARGO_PKG_VERSION").to_string(),
        globals: vec![
            ApiGlobal {
                name: "mesh".to_string(),
                kind: ApiGlobalKind::Object,
                type_name: "Mesh".to_string(),
                description: "Mesh factory namespace. Create mesh entities (cube, plane).".to_string(),
            },
            ApiGlobal {
                name: "line".to_string(),
                kind: ApiGlobalKind::Object,
                type_name: "Line".to_string(),
                description: "Line factory namespace. Create procedural line strips.".to_string(),
            },
            ApiGlobal {
                name: "scene".to_string(),
                kind: ApiGlobalKind::Object,
                type_name: "Scene".to_string(),
                description: "Scene management namespace. Add/remove entities for rendering.".to_string(),
            },
            ApiGlobal {
                name: "log".to_string(),
                kind: ApiGlobalKind::Object,
                type_name: "Log".to_string(),
                description: "Logging namespace. Use for non-fatal debugging output.".to_string(),
            },
            ApiGlobal {
                name: "dbg".to_string(),
                kind: ApiGlobalKind::Object,
                type_name: "Dbg".to_string(),
                description: "Debug namespace. Emit debug signals in analysis mode.".to_string(),
            },
            ApiGlobal {
                name: "gen".to_string(),
                kind: ApiGlobalKind::Object,
                type_name: "Gen".to_string(),
                description: "Signal generator namespace (beat-synced oscillators and noise).".to_string(),
            },
            ApiGlobal {
                name: "inputs".to_string(),
                kind: ApiGlobalKind::Object,
                type_name: "InputsSignals".to_string(),
                description: "Signal accessors namespace (Signal graphs). Note: inside `fn update(dt, inputs)`, the parameter named `inputs` shadows this global.".to_string(),
            },
            ApiGlobal {
                name: "describe".to_string(),
                kind: ApiGlobalKind::Function,
                type_name: "function".to_string(),
                description: "Host-assisted introspection. `describe(x)` returns a structured description of a value/type.".to_string(),
            },
            ApiGlobal {
                name: "help".to_string(),
                kind: ApiGlobalKind::Function,
                type_name: "function".to_string(),
                description: "Human-readable help. `help(x)` returns a short formatted summary.".to_string(),
            },
            ApiGlobal {
                name: "doc".to_string(),
                kind: ApiGlobalKind::Function,
                type_name: "function".to_string(),
                description: "Targeted documentation lookup. `doc(\"Type.member\")` returns structured docs.".to_string(),
            },
        ],
        types: vec![
            // Core value shapes
            ApiType {
                name: "Vec3".to_string(),
                kind: ApiTypeKind::Struct,
                description: "3D vector (x, y, z).".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "x".to_string(),
                        type_name: "float".to_string(),
                        description: "X component.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "y".to_string(),
                        type_name: "float".to_string(),
                        description: "Y component.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "z".to_string(),
                        type_name: "float".to_string(),
                        description: "Z component.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                ],
                methods: vec![],
            },
            ApiType {
                name: "Color".to_string(),
                kind: ApiTypeKind::Struct,
                description: "RGBA color (0.0–1.0).".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "r".to_string(),
                        type_name: "float".to_string(),
                        description: "Red (0.0–1.0).".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "g".to_string(),
                        type_name: "float".to_string(),
                        description: "Green (0.0–1.0).".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "b".to_string(),
                        type_name: "float".to_string(),
                        description: "Blue (0.0–1.0).".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "a".to_string(),
                        type_name: "float".to_string(),
                        description: "Alpha (0.0–1.0).".to_string(),
                        readonly: false,
                        optional: false,
                    },
                ],
                methods: vec![],
            },
            // Scene graph entities and namespaces
            ApiType {
                name: "MeshEntity".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "A mesh entity created by `mesh.cube()` or `mesh.plane()`.".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "position".to_string(),
                        type_name: "Vec3".to_string(),
                        description: "Position in 3D space.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "rotation".to_string(),
                        type_name: "Vec3".to_string(),
                        description: "Euler rotation in radians.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "scale".to_string(),
                        type_name: "float".to_string(),
                        description: "Uniform scale factor.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "visible".to_string(),
                        type_name: "bool".to_string(),
                        description: "Visibility flag.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                ],
                methods: vec![],
            },
            ApiType {
                name: "LineStripEntity".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "A procedural line strip created by `line.strip(options)`.".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "position".to_string(),
                        type_name: "Vec3".to_string(),
                        description: "Position in 3D space.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "rotation".to_string(),
                        type_name: "Vec3".to_string(),
                        description: "Euler rotation in radians.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "scale".to_string(),
                        type_name: "float".to_string(),
                        description: "Uniform scale factor.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "visible".to_string(),
                        type_name: "bool".to_string(),
                        description: "Visibility flag.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                    ApiProperty {
                        name: "color".to_string(),
                        type_name: "Color".to_string(),
                        description: "Line color.".to_string(),
                        readonly: false,
                        optional: false,
                    },
                ],
                methods: vec![
                    ApiMethod {
                        name: "push".to_string(),
                        description: "Add a 2D point to the strip.".to_string(),
                        params: vec![
                            ApiParam {
                                name: "x".to_string(),
                                type_name: "float".to_string(),
                                description: "X coordinate.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "y".to_string(),
                                type_name: "float".to_string(),
                                description: "Y coordinate.".to_string(),
                                optional: false,
                                default: None,
                            },
                        ],
                        returns: "void".to_string(),
                        overload_id: None,
                        example: Some("spark.push(inputs.time, inputs.amplitude);".to_string()),
                        notes: Some("Points are stored in a ring buffer (oldest points are overwritten when full).".to_string()),
                    },
                    ApiMethod {
                        name: "clear".to_string(),
                        description: "Clear all points from the strip.".to_string(),
                        params: vec![],
                        returns: "void".to_string(),
                        overload_id: None,
                        example: Some("spark.clear();".to_string()),
                        notes: None,
                    },
                ],
            },
            ApiType {
                name: "LineStripOptions".to_string(),
                kind: ApiTypeKind::Struct,
                description: "Options map for `line.strip(#{ ... })`.".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "max_points".to_string(),
                        type_name: "int".to_string(),
                        description: "Ring buffer size.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "mode".to_string(),
                        type_name: "\"line\" | \"points\"".to_string(),
                        description: "Render mode.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                ],
                methods: vec![],
            },
            ApiType {
                name: "Mesh".to_string(),
                kind: ApiTypeKind::Namespace,
                description: "Mesh factory namespace.".to_string(),
                properties: vec![],
                methods: vec![
                    ApiMethod {
                        name: "cube".to_string(),
                        description: "Create a cube mesh entity.".to_string(),
                        params: vec![],
                        returns: "MeshEntity".to_string(),
                        overload_id: None,
                        example: Some("let cube = mesh.cube();".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "plane".to_string(),
                        description: "Create a plane mesh entity.".to_string(),
                        params: vec![],
                        returns: "MeshEntity".to_string(),
                        overload_id: None,
                        example: Some("let ground = mesh.plane();".to_string()),
                        notes: None,
                    },
                ],
            },
            ApiType {
                name: "Line".to_string(),
                kind: ApiTypeKind::Namespace,
                description: "Line factory namespace.".to_string(),
                properties: vec![],
                methods: vec![ApiMethod {
                    name: "strip".to_string(),
                    description: "Create a procedural line strip.".to_string(),
                    params: vec![ApiParam {
                        name: "options".to_string(),
                        type_name: "LineStripOptions".to_string(),
                        description: "Options map (optional keys: max_points, mode).".to_string(),
                        optional: false,
                        default: None,
                    }],
                    returns: "LineStripEntity".to_string(),
                    overload_id: None,
                    example: Some("let spark = line.strip(#{ max_points: 256, mode: \"line\" });".to_string()),
                    notes: Some("Defaults: max_points=256, mode=\"line\".".to_string()),
                }],
            },
            ApiType {
                name: "Scene".to_string(),
                kind: ApiTypeKind::Namespace,
                description: "Scene management namespace.".to_string(),
                properties: vec![],
                methods: vec![
                    ApiMethod {
                        name: "add".to_string(),
                        description: "Add an entity to the render list.".to_string(),
                        params: vec![ApiParam {
                            name: "entity".to_string(),
                            type_name: "MeshEntity | LineStripEntity".to_string(),
                            description: "Entity to render.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "void".to_string(),
                        overload_id: None,
                        example: Some("scene.add(cube);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "remove".to_string(),
                        description: "Remove an entity from the render list.".to_string(),
                        params: vec![ApiParam {
                            name: "entity".to_string(),
                            type_name: "MeshEntity | LineStripEntity".to_string(),
                            description: "Entity to stop rendering.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "void".to_string(),
                        overload_id: None,
                        example: Some("scene.remove(cube);".to_string()),
                        notes: None,
                    },
                ],
            },
            ApiType {
                name: "Log".to_string(),
                kind: ApiTypeKind::Namespace,
                description: "Script logging namespace.".to_string(),
                properties: vec![],
                methods: vec![
                    ApiMethod {
                        name: "info".to_string(),
                        description: "Log an info message.".to_string(),
                        params: vec![ApiParam {
                            name: "value".to_string(),
                            type_name: "any".to_string(),
                            description: "Value to log.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "void".to_string(),
                        overload_id: None,
                        example: Some("log.info(\"hello\");".to_string()),
                        notes: Some("Log volume is limited per frame.".to_string()),
                    },
                    ApiMethod {
                        name: "warn".to_string(),
                        description: "Log a warning message.".to_string(),
                        params: vec![ApiParam {
                            name: "value".to_string(),
                            type_name: "any".to_string(),
                            description: "Value to log.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "void".to_string(),
                        overload_id: None,
                        example: Some("log.warn(\"careful\");".to_string()),
                        notes: Some("Log volume is limited per frame.".to_string()),
                    },
                    ApiMethod {
                        name: "error".to_string(),
                        description: "Log an error message.".to_string(),
                        params: vec![ApiParam {
                            name: "value".to_string(),
                            type_name: "any".to_string(),
                            description: "Value to log.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "void".to_string(),
                        overload_id: None,
                        example: Some("log.error(\"oops\");".to_string()),
                        notes: Some("Log volume is limited per frame.".to_string()),
                    },
                ],
            },
            ApiType {
                name: "Dbg".to_string(),
                kind: ApiTypeKind::Namespace,
                description: "Debug signal emission namespace.".to_string(),
                properties: vec![],
                methods: vec![ApiMethod {
                    name: "emit".to_string(),
                    description: "Emit a named debug signal value (analysis mode only).".to_string(),
                    params: vec![
                        ApiParam {
                            name: "name".to_string(),
                            type_name: "string".to_string(),
                            description: "Signal name to record.".to_string(),
                            optional: false,
                            default: None,
                        },
                        ApiParam {
                            name: "value".to_string(),
                            type_name: "float".to_string(),
                            description: "Numeric value to record.".to_string(),
                            optional: false,
                            default: None,
                        },
                    ],
                    returns: "void".to_string(),
                    overload_id: None,
                    example: Some("dbg.emit(\"energy\", 0.5);".to_string()),
                    notes: Some("In playback mode this is a no-op.".to_string()),
                }],
            },
            // Signal API
            ApiType {
                name: "Signal".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "Declarative signal computation graph (host-evaluated).".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "smooth".to_string(),
                        type_name: "SmoothBuilder".to_string(),
                        description: "Smoothing operations namespace.".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "normalise".to_string(),
                        type_name: "NormaliseBuilder".to_string(),
                        description: "Normalisation operations namespace.".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "gate".to_string(),
                        type_name: "GateBuilder".to_string(),
                        description: "Gating operations namespace.".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "pick".to_string(),
                        type_name: "PickBuilder".to_string(),
                        description: "Event extraction namespace.".to_string(),
                        readonly: true,
                        optional: false,
                    },
                ],
                methods: vec![
                    ApiMethod {
                        name: "add".to_string(),
                        description: "Add another signal.".to_string(),
                        params: vec![ApiParam {
                            name: "other".to_string(),
                            type_name: "Signal".to_string(),
                            description: "Signal to add.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: Some("signal".to_string()),
                        example: Some("inputs.spectralFlux.add(inputs.onsetEnvelope)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "add".to_string(),
                        description: "Add a constant value.".to_string(),
                        params: vec![ApiParam {
                            name: "value".to_string(),
                            type_name: "float".to_string(),
                            description: "Constant to add.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: Some("scalar".to_string()),
                        example: Some("inputs.amplitude.add(0.5)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "mul".to_string(),
                        description: "Multiply by another signal.".to_string(),
                        params: vec![ApiParam {
                            name: "other".to_string(),
                            type_name: "Signal".to_string(),
                            description: "Signal to multiply by.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.amplitude.mul(inputs.onsetEnvelope)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "scale".to_string(),
                        description: "Multiply by a constant factor.".to_string(),
                        params: vec![ApiParam {
                            name: "factor".to_string(),
                            type_name: "float".to_string(),
                            description: "Scale factor.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.amplitude.scale(2.0)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "mix".to_string(),
                        description: "Linear blend between this signal and another.".to_string(),
                        params: vec![
                            ApiParam {
                                name: "other".to_string(),
                                type_name: "Signal".to_string(),
                                description: "Other signal.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "weight".to_string(),
                                type_name: "float".to_string(),
                                description: "0.0 = this, 1.0 = other.".to_string(),
                                optional: false,
                                default: Some(serde_json::Value::from(0.5)),
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.amplitude.mix(inputs.spectralFlux, 0.5)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "probe".to_string(),
                        description: "Attach a debug probe to emit values during host evaluation.".to_string(),
                        params: vec![ApiParam {
                            name: "name".to_string(),
                            type_name: "string".to_string(),
                            description: "Probe name.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.onsetEnvelope.probe(\"onset\")".to_string()),
                        notes: Some("Use with analysis mode / host evaluation; this does not print.".to_string()),
                    },
                    ApiMethod {
                        name: "clamp".to_string(),
                        description: "Clamp signal to [min, max].".to_string(),
                        params: vec![
                            ApiParam {
                                name: "min".to_string(),
                                type_name: "float".to_string(),
                                description: "Lower bound.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "max".to_string(),
                                type_name: "float".to_string(),
                                description: "Upper bound.".to_string(),
                                optional: false,
                                default: None,
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.amplitude.clamp(0.0, 1.0)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "floor".to_string(),
                        description: "Round down.".to_string(),
                        params: vec![],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.beatPosition.floor()".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "ceil".to_string(),
                        description: "Round up.".to_string(),
                        params: vec![],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.beatPosition.ceil()".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "diff".to_string(),
                        description: "Approximate derivative (rate of change).".to_string(),
                        params: vec![],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.amplitude.diff()".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "integrate".to_string(),
                        description: "Cumulative sum with optional decay (in beats).".to_string(),
                        params: vec![ApiParam {
                            name: "decay_beats".to_string(),
                            type_name: "float".to_string(),
                            description: "0 = no decay.".to_string(),
                            optional: false,
                            default: Some(serde_json::Value::from(0.0)),
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.onsetEnvelope.integrate(0.5)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "delay".to_string(),
                        description: "Delay the signal by N beats.".to_string(),
                        params: vec![ApiParam {
                            name: "beats".to_string(),
                            type_name: "float".to_string(),
                            description: "Delay amount in beats.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.onsetEnvelope.delay(0.25)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "anticipate".to_string(),
                        description: "Look ahead by N beats (input signals only).".to_string(),
                        params: vec![ApiParam {
                            name: "beats".to_string(),
                            type_name: "float".to_string(),
                            description: "Lookahead in beats.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.onsetEnvelope.anticipate(0.1)".to_string()),
                        notes: Some("For derived signals this may be a no-op.".to_string()),
                    },
                    ApiMethod {
                        name: "interpolate".to_string(),
                        description: "Use linear interpolation sampling.".to_string(),
                        params: vec![],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.spectralCentroid.interpolate()".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "peak".to_string(),
                        description: "Use peak-preserving sampling (default).".to_string(),
                        params: vec![],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.onsetEnvelope.peak()".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "peak_window".to_string(),
                        description: "Peak-preserving sampling with custom window (beats).".to_string(),
                        params: vec![ApiParam {
                            name: "beats".to_string(),
                            type_name: "float".to_string(),
                            description: "Window size in beats.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.energy.peak_window(0.25)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "peak_window_sec".to_string(),
                        description: "Peak-preserving sampling with custom window (seconds).".to_string(),
                        params: vec![ApiParam {
                            name: "seconds".to_string(),
                            type_name: "float".to_string(),
                            description: "Window size in seconds.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.energy.peak_window_sec(0.05)".to_string()),
                        notes: None,
                    },
                ],
            },
            ApiType {
                name: "SmoothBuilder".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "Smoothing operations (returned by `signal.smooth`).".to_string(),
                properties: vec![],
                methods: vec![
                    ApiMethod {
                        name: "moving_average".to_string(),
                        description: "Moving average over a window of N beats.".to_string(),
                        params: vec![ApiParam {
                            name: "beats".to_string(),
                            type_name: "float".to_string(),
                            description: "Window size in beats.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.onsetEnvelope.smooth.moving_average(0.5)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "exponential".to_string(),
                        description: "Asymmetric exponential smoothing in beats.".to_string(),
                        params: vec![
                            ApiParam {
                                name: "attack_beats".to_string(),
                                type_name: "float".to_string(),
                                description: "Attack time in beats (rising).".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "release_beats".to_string(),
                                type_name: "float".to_string(),
                                description: "Release time in beats (falling).".to_string(),
                                optional: false,
                                default: None,
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.amplitude.smooth.exponential(0.1, 0.5)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "gaussian".to_string(),
                        description: "Gaussian blur with sigma in beats.".to_string(),
                        params: vec![ApiParam {
                            name: "sigma_beats".to_string(),
                            type_name: "float".to_string(),
                            description: "Sigma in beats.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.spectralCentroid.smooth.gaussian(0.25)".to_string()),
                        notes: None,
                    },
                ],
            },
            ApiType {
                name: "NormaliseBuilder".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "Normalisation operations (returned by `signal.normalise`).".to_string(),
                properties: vec![],
                methods: vec![
                    ApiMethod {
                        name: "global".to_string(),
                        description: "Min-max normalisation using whole-track statistics.".to_string(),
                        params: vec![],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.amplitude.normalise.global()".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "robust".to_string(),
                        description: "Percentile-based normalisation (5th–95th).".to_string(),
                        params: vec![],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.spectralFlux.normalise.robust()".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "to_range".to_string(),
                        description: "Map to a custom output range.".to_string(),
                        params: vec![
                            ApiParam {
                                name: "min".to_string(),
                                type_name: "float".to_string(),
                                description: "Output min.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "max".to_string(),
                                type_name: "float".to_string(),
                                description: "Output max.".to_string(),
                                optional: false,
                                default: None,
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.amplitude.normalise.to_range(0.0, 1.0)".to_string()),
                        notes: None,
                    },
                ],
            },
            ApiType {
                name: "GateBuilder".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "Gating operations (returned by `signal.gate`).".to_string(),
                properties: vec![],
                methods: vec![
                    ApiMethod {
                        name: "threshold".to_string(),
                        description: "Binary gate: 1.0 if >= threshold else 0.0.".to_string(),
                        params: vec![ApiParam {
                            name: "threshold".to_string(),
                            type_name: "float".to_string(),
                            description: "Threshold value.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.onsetEnvelope.gate.threshold(0.7)".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "hysteresis".to_string(),
                        description: "Schmitt trigger gate (on/off thresholds).".to_string(),
                        params: vec![
                            ApiParam {
                                name: "on_threshold".to_string(),
                                type_name: "float".to_string(),
                                description: "Must exceed to turn on.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "off_threshold".to_string(),
                                type_name: "float".to_string(),
                                description: "Must drop below to turn off.".to_string(),
                                optional: false,
                                default: None,
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("inputs.amplitude.gate.hysteresis(0.6, 0.4)".to_string()),
                        notes: None,
                    },
                ],
            },
            ApiType {
                name: "PickEventsOptions".to_string(),
                kind: ApiTypeKind::Struct,
                description: "Options map for `signal.pick.events(#{ ... })`.".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "hysteresis_beats".to_string(),
                        type_name: "float".to_string(),
                        description: "Minimum time between events in beats. Default: 0.25.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "target_density".to_string(),
                        type_name: "float".to_string(),
                        description: "Target events per beat. Default: 1.0.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "similarity_tolerance".to_string(),
                        type_name: "float".to_string(),
                        description: "Similarity clustering tolerance (0.0–1.0). Default: 0.15.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "phase_bias".to_string(),
                        type_name: "float".to_string(),
                        description: "Prefer on-beat events (0.0–1.0). Default: 0.0.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "min_threshold".to_string(),
                        type_name: "float".to_string(),
                        description: "Minimum absolute threshold. Default: 0.1.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "adaptive_factor".to_string(),
                        type_name: "float".to_string(),
                        description: "Adaptive threshold factor. Default: 0.5.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "weight_mode".to_string(),
                        type_name: "\"peak_height\" | \"integrated_energy\"".to_string(),
                        description: "How to assign event weights. Default: peak_height.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "energy_window_beats".to_string(),
                        type_name: "float".to_string(),
                        description: "If weight_mode is integrated_energy, integration window in beats. Default: 0.25.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                ],
                methods: vec![],
            },
            ApiType {
                name: "PickBuilder".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "Event extraction operations (returned by `signal.pick`).".to_string(),
                properties: vec![],
                methods: vec![ApiMethod {
                    name: "events".to_string(),
                    description: "Extract an EventStream from a Signal using peak-picking.".to_string(),
                    params: vec![ApiParam {
                        name: "options".to_string(),
                        type_name: "PickEventsOptions".to_string(),
                        description: "Options map.".to_string(),
                        optional: false,
                        default: None,
                    }],
                    returns: "EventStream".to_string(),
                    overload_id: None,
                    example: Some(
                        "let events = inputs.onsetEnvelope.pick.events(#{ target_density: 2.0 });"
                            .to_string(),
                    ),
                    notes: Some("In playback mode, this may return an empty stream.".to_string()),
                }],
            },
            ApiType {
                name: "Event".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "A single extracted event.".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "time".to_string(),
                        type_name: "float".to_string(),
                        description: "Event time in seconds.".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "weight".to_string(),
                        type_name: "float".to_string(),
                        description: "Event weight (meaning depends on weight_mode).".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "beat_position".to_string(),
                        type_name: "float".to_string(),
                        description: "Beat position if available, else 0.0.".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "beat_phase".to_string(),
                        type_name: "float".to_string(),
                        description: "Phase within beat if available, else 0.0.".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "cluster_id".to_string(),
                        type_name: "int".to_string(),
                        description: "Cluster ID if available, else -1.".to_string(),
                        readonly: true,
                        optional: false,
                    },
                ],
                methods: vec![],
            },
            ApiType {
                name: "ToSignalOptions".to_string(),
                kind: ApiTypeKind::Struct,
                description: "Options map for `event_stream.to_signal(#{ ... })`.".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "envelope".to_string(),
                        type_name: "string".to_string(),
                        description: "Envelope shape. Default: \"impulse\".".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "attack_beats".to_string(),
                        type_name: "float".to_string(),
                        description: "Attack in beats. Default: 0.1.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "decay_beats".to_string(),
                        type_name: "float".to_string(),
                        description: "Decay in beats. Default: 0.5.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "sustain_level".to_string(),
                        type_name: "float".to_string(),
                        description: "ADSR sustain level. Default: 0.7.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "sustain_beats".to_string(),
                        type_name: "float".to_string(),
                        description: "ADSR sustain time in beats. Default: 0.5.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "release_beats".to_string(),
                        type_name: "float".to_string(),
                        description: "ADSR release in beats. Default: 0.3.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "width_beats".to_string(),
                        type_name: "float".to_string(),
                        description: "Gaussian width in beats. Default: 0.25.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "easing".to_string(),
                        type_name: "string".to_string(),
                        description: "Easing function. Default: \"linear\".".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "overlap_mode".to_string(),
                        type_name: "string".to_string(),
                        description: "How to combine overlapping envelopes. Default: \"sum\".".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "group_within_beats".to_string(),
                        type_name: "float".to_string(),
                        description: "Group nearby events before shaping. Default: null.".to_string(),
                        readonly: false,
                        optional: true,
                    },
                    ApiProperty {
                        name: "merge_mode".to_string(),
                        type_name: "string".to_string(),
                        description: "How to merge grouped events. Default: \"sum\".".to_string(),
                        readonly: false,
                        optional: true,
                    },
                ],
                methods: vec![],
            },
            ApiType {
                name: "EventStream".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "An immutable, time-ordered stream of events.".to_string(),
                properties: vec![],
                methods: vec![
                    ApiMethod {
                        name: "len".to_string(),
                        description: "Number of events.".to_string(),
                        params: vec![],
                        returns: "int".to_string(),
                        overload_id: None,
                        example: Some("let n = events.len();".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "is_empty".to_string(),
                        description: "True if there are no events.".to_string(),
                        params: vec![],
                        returns: "bool".to_string(),
                        overload_id: None,
                        example: Some("if events.is_empty() { ... }".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "get".to_string(),
                        description: "Get an event by index (or () if out of range).".to_string(),
                        params: vec![ApiParam {
                            name: "index".to_string(),
                            type_name: "int".to_string(),
                            description: "0-based index.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Event | void".to_string(),
                        overload_id: None,
                        example: Some("let e = events.get(0);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "to_array".to_string(),
                        description: "Convert to an array for iteration.".to_string(),
                        params: vec![],
                        returns: "array<Event>".to_string(),
                        overload_id: None,
                        example: Some("for e in events.to_array() { ... }".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "time_span".to_string(),
                        description: "Return [start, end] times (or [] if empty).".to_string(),
                        params: vec![],
                        returns: "array<float>".to_string(),
                        overload_id: None,
                        example: Some("let span = events.time_span();".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "max_weight".to_string(),
                        description: "Maximum event weight (or 0.0 if empty).".to_string(),
                        params: vec![],
                        returns: "float".to_string(),
                        overload_id: None,
                        example: Some("let w = events.max_weight();".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "min_weight".to_string(),
                        description: "Minimum event weight (or 0.0 if empty).".to_string(),
                        params: vec![],
                        returns: "float".to_string(),
                        overload_id: None,
                        example: Some("let w = events.min_weight();".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "to_signal".to_string(),
                        description: "Convert events to an impulse Signal.".to_string(),
                        params: vec![],
                        returns: "Signal".to_string(),
                        overload_id: Some("impulse".to_string()),
                        example: Some("let impulses = events.to_signal();".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "to_signal".to_string(),
                        description: "Convert events to a shaped Signal.".to_string(),
                        params: vec![ApiParam {
                            name: "options".to_string(),
                            type_name: "ToSignalOptions".to_string(),
                            description: "Envelope shaping options.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: Some("options".to_string()),
                        example: Some(
                            "let env = events.to_signal(#{ envelope: \"attack_decay\", attack_beats: 0.05, decay_beats: 0.5 });"
                                .to_string(),
                        ),
                        notes: None,
                    },
                    ApiMethod {
                        name: "filter_time".to_string(),
                        description: "Filter events to a time range [start, end).".to_string(),
                        params: vec![
                            ApiParam {
                                name: "start".to_string(),
                                type_name: "float".to_string(),
                                description: "Start time (seconds).".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "end".to_string(),
                                type_name: "float".to_string(),
                                description: "End time (seconds).".to_string(),
                                optional: false,
                                default: None,
                            },
                        ],
                        returns: "EventStream".to_string(),
                        overload_id: None,
                        example: Some("let later = events.filter_time(30.0, 45.0);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "filter_weight".to_string(),
                        description: "Filter events by minimum weight.".to_string(),
                        params: vec![ApiParam {
                            name: "min_weight".to_string(),
                            type_name: "float".to_string(),
                            description: "Minimum weight.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "EventStream".to_string(),
                        overload_id: None,
                        example: Some("let strong = events.filter_weight(0.5);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "limit".to_string(),
                        description: "Limit to the first N events.".to_string(),
                        params: vec![ApiParam {
                            name: "max_events".to_string(),
                            type_name: "int".to_string(),
                            description: "Maximum number of events.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "EventStream".to_string(),
                        overload_id: None,
                        example: Some("let first = events.limit(10);".to_string()),
                        notes: None,
                    },
                ],
            },
            ApiType {
                name: "Gen".to_string(),
                kind: ApiTypeKind::Namespace,
                description: "Signal generator namespace.".to_string(),
                properties: vec![],
                methods: vec![
                    ApiMethod {
                        name: "sin".to_string(),
                        description: "Sine wave oscillator synced to beats.".to_string(),
                        params: vec![
                            ApiParam {
                                name: "freq_beats".to_string(),
                                type_name: "float".to_string(),
                                description: "Frequency in cycles per beat.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "phase".to_string(),
                                type_name: "float".to_string(),
                                description: "Phase offset.".to_string(),
                                optional: false,
                                default: Some(serde_json::Value::from(0.0)),
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("let s = gen.sin(1.0, 0.0);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "square".to_string(),
                        description: "Square wave oscillator.".to_string(),
                        params: vec![
                            ApiParam {
                                name: "freq_beats".to_string(),
                                type_name: "float".to_string(),
                                description: "Frequency in cycles per beat.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "phase".to_string(),
                                type_name: "float".to_string(),
                                description: "Phase offset.".to_string(),
                                optional: false,
                                default: Some(serde_json::Value::from(0.0)),
                            },
                            ApiParam {
                                name: "duty".to_string(),
                                type_name: "float".to_string(),
                                description: "Duty cycle (0.0–1.0).".to_string(),
                                optional: false,
                                default: Some(serde_json::Value::from(0.5)),
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("let s = gen.square(1.0, 0.0, 0.5);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "triangle".to_string(),
                        description: "Triangle wave oscillator synced to beats.".to_string(),
                        params: vec![
                            ApiParam {
                                name: "freq_beats".to_string(),
                                type_name: "float".to_string(),
                                description: "Frequency in cycles per beat.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "phase".to_string(),
                                type_name: "float".to_string(),
                                description: "Phase offset.".to_string(),
                                optional: false,
                                default: Some(serde_json::Value::from(0.0)),
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("let s = gen.triangle(1.0, 0.0);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "saw".to_string(),
                        description: "Sawtooth oscillator synced to beats.".to_string(),
                        params: vec![
                            ApiParam {
                                name: "freq_beats".to_string(),
                                type_name: "float".to_string(),
                                description: "Frequency in cycles per beat.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "phase".to_string(),
                                type_name: "float".to_string(),
                                description: "Phase offset.".to_string(),
                                optional: false,
                                default: Some(serde_json::Value::from(0.0)),
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("let s = gen.saw(1.0, 0.0);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "noise".to_string(),
                        description: "Noise generator (white or pink).".to_string(),
                        params: vec![
                            ApiParam {
                                name: "noise_type".to_string(),
                                type_name: "\"white\" | \"pink\"".to_string(),
                                description: "Noise type.".to_string(),
                                optional: false,
                                default: Some(serde_json::Value::from("white")),
                            },
                            ApiParam {
                                name: "seed".to_string(),
                                type_name: "int".to_string(),
                                description: "Deterministic seed.".to_string(),
                                optional: false,
                                default: Some(serde_json::Value::from(0)),
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("let n = gen.noise(\"pink\", 42);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "perlin".to_string(),
                        description: "1D Perlin noise synced to beats.".to_string(),
                        params: vec![
                            ApiParam {
                                name: "scale_beats".to_string(),
                                type_name: "float".to_string(),
                                description: "Scale in beats.".to_string(),
                                optional: false,
                                default: None,
                            },
                            ApiParam {
                                name: "seed".to_string(),
                                type_name: "int".to_string(),
                                description: "Deterministic seed.".to_string(),
                                optional: false,
                                default: Some(serde_json::Value::from(0)),
                            },
                        ],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("let n = gen.perlin(1.0, 42);".to_string()),
                        notes: None,
                    },
                    ApiMethod {
                        name: "constant".to_string(),
                        description: "Constant-valued signal.".to_string(),
                        params: vec![ApiParam {
                            name: "value".to_string(),
                            type_name: "float".to_string(),
                            description: "Constant value.".to_string(),
                            optional: false,
                            default: None,
                        }],
                        returns: "Signal".to_string(),
                        overload_id: None,
                        example: Some("let one = gen.constant(1.0);".to_string()),
                        notes: None,
                    },
                ],
            },
            // Inputs namespace (Signals)
            ApiType {
                name: "InputsSignals".to_string(),
                kind: ApiTypeKind::Namespace,
                description: "Global signal accessors namespace. Properties return `Signal` objects.".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "time".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Playback time in seconds.".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "dt".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Delta time in seconds.".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "amplitude".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Audio amplitude (normalized).".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "flux".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Spectral flux (alias for `spectralFlux` when provided).".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "spectralCentroid".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Spectral centroid (brightness).".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "spectralFlux".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Spectral flux (rate of spectral change).".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "onsetEnvelope".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Onset detection envelope.".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "searchSimilarity".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Search similarity curve (0–1).".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "beatPosition".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Continuous beat position (beatIndex + beatPhase).".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "beatIndex".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Current beat index (integer-valued).".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "beatPhase".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Phase within current beat (0–1).".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "bpm".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Tempo in beats per minute.".to_string(),
                        readonly: true,
                        optional: true,
                    },
                    ApiProperty {
                        name: "bands".to_string(),
                        type_name: "Bands".to_string(),
                        description: "Band-scoped signal accessors: `inputs.bands[\"Bass\"].energy`.".to_string(),
                        readonly: true,
                        optional: true,
                    },
                ],
                methods: vec![],
            },
            ApiType {
                name: "Bands".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "Band-scoped signal accessors (string-keyed map).".to_string(),
                properties: vec![],
                methods: vec![],
            },
            ApiType {
                name: "BandSignals".to_string(),
                kind: ApiTypeKind::Opaque,
                description: "Signals available for a specific band key.".to_string(),
                properties: vec![
                    ApiProperty {
                        name: "energy".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Band amplitude envelope (0–1).".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "onset".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Band onset strength (0–1).".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "flux".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Band spectral flux (0–1).".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "amplitude".to_string(),
                        type_name: "Signal".to_string(),
                        description: "Alias for energy.".to_string(),
                        readonly: true,
                        optional: false,
                    },
                    ApiProperty {
                        name: "events".to_string(),
                        type_name: "EventStream".to_string(),
                        description: "Band-scoped events (may be empty).".to_string(),
                        readonly: true,
                        optional: false,
                    },
                ],
                methods: vec![],
            },
        ],
    }
}

pub fn script_api_metadata_json() -> String {
    serde_json::to_string(&script_api_metadata()).unwrap_or_else(|_| "{}".to_string())
}
