/**
 * Demo audio files available from the public/audio folder.
 * This list is auto-generated by scripts/generate-demo-audio-list.mjs at build time.
 */

import demoAudioList from "./generated/demo-audio-list.json";

export interface DemoAudioFile {
  /** Display name shown in the UI */
  name: string;
  /** Path relative to /public (will be fetched from this URL) */
  path: string;
  /** Original filename */
  filename: string;
  /** File size in bytes */
  size: number;
  /** Human-readable file size */
  sizeFormatted: string;
}

export const DEMO_AUDIO_FILES: DemoAudioFile[] = demoAudioList;
